import type {
  BookingEntry,
  BookingPost,
  MiniCalendarDay,
} from "@/features/booking/types";

export const BOOKING_POSTS: BookingPost[] = [
  { id: "post-1", label: "ПОСТ 1" },
  { id: "post-2", label: "ПОСТ 2" },
  { id: "post-3", label: "ПОСТ 3" },
];

export const BOOKING_DAY_HOURS = [
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
];

export const BOOKING_CLIENT_OPTIONS = [
  "Не выбран (Анонимный)",
  "Андрей Климов · BMW 3 серии",
  "Елена Сафонова · Brabus V12",
  "Олег Никитин · LADA Largus",
  "Мария Волкова · Kia K5",
  "Игорь Лебедев · Toyota Camry",
];

export const BOOKING_DAY_ENTRIES: BookingEntry[] = [
  {
    id: "booking-day-1",
    groupId: "booking-day-1",
    branchId: "branch-gotvalda-9",
    clientId: "client-denis-pavlov",
    anonymous: false,
    client: "Андрей Климов",
    phone: "+7 900 100-10-01",
    car: "BMW 3 серии",
    date: "2026-03-15",
    startTime: "12:30",
    endTime: "13:15",
    postId: "post-2",
    service: "Комплекс шиномонтажа",
    comment: "Переобувка комплекта",
  },
  {
    id: "booking-day-2",
    groupId: "booking-day-2",
    branchId: "branch-gotvalda-9",
    clientId: null,
    anonymous: true,
    client: "Анонимный клиент",
    phone: "",
    car: "LADA Vesta",
    date: "2026-03-15",
    startTime: "16:00",
    endTime: "16:45",
    postId: "post-1",
    service: "Балансировка",
  },
];

export const BOOKING_NEW_ENTRY_PREVIEW: BookingEntry = {
  id: "booking-preview-1",
  groupId: "booking-preview-1",
  branchId: "branch-gotvalda-9",
  clientId: null,
  anonymous: true,
  client: "Анонимный клиент",
  phone: "",
  car: "Не указан",
  date: "2026-03-15",
  startTime: "12:45",
  endTime: "15:15",
  postId: "post-2",
  service: "Комплекс шиномонтажа",
  comment: "",
};

export const BOOKING_MONTH_ENTRIES: BookingEntry[] = [
  {
    id: "booking-month-1",
    groupId: "booking-month-1",
    branchId: "branch-gotvalda-9",
    clientId: "client-denis-pavlov",
    anonymous: false,
    client: "Андрей Климов",
    phone: "+7 900 100-10-01",
    car: "BMW 3 серии",
    date: "2026-03-03",
    startTime: "10:00",
    endTime: "11:00",
    postId: "post-1",
    service: "Шиномонтаж",
  },
  {
    id: "booking-month-2",
    groupId: "booking-month-2",
    branchId: "branch-gotvalda-9",
    clientId: "client-natalya-orlova",
    anonymous: false,
    client: "Елена Сафонова",
    phone: "+7 900 200-20-02",
    car: "Brabus V12",
    date: "2026-03-10",
    startTime: "12:30",
    endTime: "13:30",
    postId: "post-2",
    service: "Датчики давления",
  },
  {
    id: "booking-month-3",
    groupId: "booking-month-3",
    branchId: "branch-gotvalda-9",
    clientId: "client-sergey-volkov",
    anonymous: false,
    client: "Игорь Лебедев",
    phone: "+7 900 500-50-05",
    car: "Toyota Camry",
    date: "2026-03-15",
    startTime: "14:00",
    endTime: "15:00",
    postId: "post-3",
    service: "Комплекс шиномонтажа",
  },
  {
    id: "booking-month-4",
    groupId: "booking-month-4",
    branchId: "branch-gotvalda-9",
    clientId: null,
    anonymous: true,
    client: "Анонимный клиент",
    phone: "",
    car: "Toyota Camry",
    date: "2026-03-21",
    startTime: "09:30",
    endTime: "10:30",
    postId: "post-1",
    service: "Балансировка",
  },
];

export const BOOKING_MINI_CALENDAR_DAYS: MiniCalendarDay[] = [
  { key: "empty-0", label: "", inCurrentMonth: false },
  { key: "empty-1", label: "", inCurrentMonth: false },
  { key: "01", label: "1", inCurrentMonth: true },
  { key: "02", label: "2", inCurrentMonth: true },
  { key: "03", label: "3", inCurrentMonth: true },
  { key: "04", label: "4", inCurrentMonth: true },
  { key: "05", label: "5", inCurrentMonth: true },
  { key: "06", label: "6", inCurrentMonth: true },
  { key: "07", label: "7", inCurrentMonth: true },
  { key: "08", label: "8", inCurrentMonth: true },
  { key: "09", label: "9", inCurrentMonth: true },
  { key: "10", label: "10", inCurrentMonth: true },
  { key: "11", label: "11", inCurrentMonth: true },
  { key: "12", label: "12", inCurrentMonth: true },
  { key: "13", label: "13", inCurrentMonth: true },
  { key: "14", label: "14", inCurrentMonth: true },
  { key: "15", label: "15", inCurrentMonth: true, isSelected: true },
  { key: "16", label: "16", inCurrentMonth: true },
  { key: "17", label: "17", inCurrentMonth: true },
  { key: "18", label: "18", inCurrentMonth: true },
  { key: "19", label: "19", inCurrentMonth: true },
  { key: "20", label: "20", inCurrentMonth: true },
  { key: "21", label: "21", inCurrentMonth: true },
  { key: "22", label: "22", inCurrentMonth: true },
  { key: "23", label: "23", inCurrentMonth: true },
  { key: "24", label: "24", inCurrentMonth: true },
  { key: "25", label: "25", inCurrentMonth: true },
  { key: "26", label: "26", inCurrentMonth: true },
  { key: "27", label: "27", inCurrentMonth: true },
  { key: "28", label: "28", inCurrentMonth: true },
  { key: "29", label: "29", inCurrentMonth: true },
  { key: "30", label: "30", inCurrentMonth: true },
  { key: "31", label: "31", inCurrentMonth: true },
];

export const BOOKING_MONTH_GRID = [
  { label: "ПН", day: "", entries: [] },
  { label: "ВТ", day: "", entries: [] },
  { label: "СР", day: "", entries: [] },
  { label: "ЧТ", day: "", entries: [] },
  { label: "ПТ", day: "", entries: [] },
  { label: "СБ", day: "1", entries: [] },
  { label: "ВС", day: "2", entries: [] },
  { label: "ПН", day: "3", entries: [BOOKING_MONTH_ENTRIES[0]] },
  { label: "ВТ", day: "4", entries: [] },
  { label: "СР", day: "5", entries: [] },
  { label: "ЧТ", day: "6", entries: [] },
  { label: "ПТ", day: "7", entries: [] },
  { label: "СБ", day: "8", entries: [] },
  { label: "ВС", day: "9", entries: [] },
  { label: "ПН", day: "10", entries: [BOOKING_MONTH_ENTRIES[1]] },
  { label: "ВТ", day: "11", entries: [] },
  { label: "СР", day: "12", entries: [] },
  { label: "ЧТ", day: "13", entries: [] },
  { label: "ПТ", day: "14", entries: [] },
  { label: "СБ", day: "15", entries: [BOOKING_MONTH_ENTRIES[2]] },
  { label: "ВС", day: "16", entries: [] },
  { label: "ПН", day: "17", entries: [] },
  { label: "ВТ", day: "18", entries: [] },
  { label: "СР", day: "19", entries: [] },
  { label: "ЧТ", day: "20", entries: [] },
  { label: "ПТ", day: "21", entries: [BOOKING_MONTH_ENTRIES[3]] },
  { label: "СБ", day: "22", entries: [] },
  { label: "ВС", day: "23", entries: [] },
  { label: "ПН", day: "24", entries: [] },
  { label: "ВТ", day: "25", entries: [] },
  { label: "СР", day: "26", entries: [] },
  { label: "ЧТ", day: "27", entries: [] },
  { label: "ПТ", day: "28", entries: [] },
  { label: "СБ", day: "29", entries: [] },
  { label: "ВС", day: "30", entries: [] },
  { label: "ПН", day: "31", entries: [] },
];
