import type { DemoClient } from "@/features/clients/types";

const DEFAULT_SOURCE_OPTIONS = [
  "Не выбран",
  "Интернет",
  "Рекомендация",
  "Постоянный клиент",
  "Онлайн-запись",
  "Instagram",
];

export const DEMO_CLIENTS: DemoClient[] = [
  {
    id: "denis-pavlov",
    name: "Андрей Климов",
    shortName: "Андрей Климов",
    firstName: "Андрей",
    lastName: "Климов",
    middleName: "",
    phone: "+7 900 100-10-01",
    email: "",
    registrationDate: "01.03.2026",
    source: "Постоянный клиент",
    sourceOptions: [...DEFAULT_SOURCE_OPTIONS],
    note: "BMW 3 серии. Предпочитает вечерние смены.",
    lastVisitDate: "16.03.2026",
    ordersCount: 2,
    averageCheck: 3640,
    totalSpent: 7280,
    averageVisitGapLabel: "1 день",
    vehicles: [
      {
        id: "vehicle-bmw-3",
        label: "BMW 3 серии",
        brand: "BMW",
        model: "3 серии",
        plateNumber: "О313АА 196",
        radius: "R17",
        totalSpent: 7280,
      },
    ],
    orders: [
      {
        id: "client-order-60",
        orderNumber: "60",
        dateTime: "16 марта 2026, 10:05",
        branch: "Северный",
        carLabel: "BMW 3 серии · R17",
        amount: 3800,
        status: "Оплачен",
        servicesLabel: "Комплекс шиномонтажа",
      },
      {
        id: "client-order-58",
        orderNumber: "58",
        dateTime: "15 марта 2026, 10:15",
        branch: "Северный",
        carLabel: "BMW 3 серии · R17",
        amount: 3480,
        status: "Оплачен",
        servicesLabel: "Комплекс шиномонтажа",
      },
    ],
    visits: [
      {
        id: "visit-denis-1",
        dateTime: "16.03.2026 · 10:05",
        branch: "Северный",
        post: "ПОСТ 2",
        serviceLabel: "Комплекс шиномонтажа",
        resultLabel: "Оплачено",
      },
      {
        id: "visit-denis-2",
        dateTime: "15.03.2026 · 10:15",
        branch: "Северный",
        post: "ПОСТ 1",
        serviceLabel: "Комплекс шиномонтажа",
        resultLabel: "Оплачено",
      },
    ],
    storages: [
      {
        id: "storage-denis-1",
        name: "Комплект колёс BMW R17",
        status: "На хранении до 30.09.2026",
      },
    ],
    bookings: [
      {
        id: "booking-denis-1",
        date: "19.03.2026 · 18:30",
        note: "Весенний переобув",
      },
    ],
  },
  {
    id: "natalya-orlova",
    name: "Елена Сафонова",
    shortName: "Елена Сафонова",
    firstName: "Елена",
    lastName: "Сафонова",
    middleName: "",
    phone: "+7 900 200-20-02",
    email: "",
    registrationDate: "09.03.2026",
    source: "Instagram",
    sourceOptions: [...DEFAULT_SOURCE_OPTIONS],
    note: "Brabus V12. Просит фото до/после.",
    lastVisitDate: "15.03.2026",
    ordersCount: 2,
    averageCheck: 7000,
    totalSpent: 14000,
    averageVisitGapLabel: "5 дней",
    vehicles: [
      {
        id: "vehicle-brabus-v12",
        label: "Brabus V12",
        brand: "Brabus",
        model: "V12",
        plateNumber: "А001МР 196",
        radius: "R20",
        totalSpent: 6520,
      },
      {
        id: "vehicle-g63",
        label: "Mercedes-Benz G63",
        brand: "Mercedes-Benz",
        model: "G63",
        plateNumber: "Т818ТТ 196",
        radius: "R21",
        totalSpent: 7480,
      },
    ],
    orders: [
      {
        id: "client-order-59",
        orderNumber: "59",
        dateTime: "15 марта 2026, 17:52",
        branch: "Северный",
        carLabel: "Brabus V12 · R20",
        amount: 6520,
        status: "Оплачен",
        servicesLabel: "Комплекс шиномонтажа",
      },
      {
        id: "client-order-45",
        orderNumber: "45",
        dateTime: "10 марта 2026, 12:30",
        branch: "Центральный",
        carLabel: "Mercedes-Benz G63 · R21",
        amount: 7480,
        status: "Оплачен",
        servicesLabel: "Балансировка, правка литого диска",
      },
    ],
    visits: [
      {
        id: "visit-natalya-1",
        dateTime: "15.03.2026 · 17:52",
        branch: "Северный",
        post: "ПОСТ 3",
        serviceLabel: "Комплекс шиномонтажа",
        resultLabel: "Оплачено",
      },
      {
        id: "visit-natalya-2",
        dateTime: "10.03.2026 · 12:30",
        branch: "Центральный",
        post: "ПОСТ 2",
        serviceLabel: "Правка литого диска",
        resultLabel: "Оплачено",
      },
    ],
    storages: [
      {
        id: "storage-natalya-1",
        name: "Комплект шин Pirelli R20",
        status: "На хранении до 01.10.2026",
      },
    ],
    bookings: [],
  },
  {
    id: "boris-zelen",
    name: "Олег Никитин",
    shortName: "Олег Никитин",
    firstName: "Олег",
    lastName: "Никитин",
    middleName: "",
    phone: "+7 900 300-30-03",
    email: "",
    registrationDate: "05.03.2026",
    source: "Рекомендация",
    sourceOptions: [...DEFAULT_SOURCE_OPTIONS],
    note: "LADA Largus.",
    lastVisitDate: "16.03.2026",
    ordersCount: 1,
    averageCheck: 1980,
    totalSpent: 1980,
    averageVisitGapLabel: "—",
    vehicles: [
      {
        id: "vehicle-lada-largus",
        label: "LADA Largus",
        brand: "LADA",
        model: "Largus",
        plateNumber: "Е220КУ 196",
        radius: "R15",
        totalSpent: 1980,
      },
    ],
    orders: [
      {
        id: "client-order-61",
        orderNumber: "61",
        dateTime: "16 марта 2026, 11:40",
        branch: "Северный",
        carLabel: "LADA Largus · R15",
        amount: 1980,
        status: "Оплачен",
        servicesLabel: "Балансировка",
      },
    ],
    visits: [
      {
        id: "visit-boris-1",
        dateTime: "16.03.2026 · 11:40",
        branch: "Северный",
        post: "ПОСТ 2",
        serviceLabel: "Балансировка",
        resultLabel: "Оплачено",
      },
    ],
    storages: [
      {
        id: "storage-boris-1",
        name: "Комплект шин Nokian R15",
        status: "Выдано клиенту 13.03.2026",
      },
    ],
    bookings: [],
  },
  {
    id: "anna-sokolova",
    name: "Мария Волкова",
    shortName: "Мария Волкова",
    firstName: "Мария",
    lastName: "Волкова",
    middleName: "",
    phone: "+7 900 400-40-04",
    email: "",
    registrationDate: "11.03.2026",
    source: "Повторный визит",
    sourceOptions: [...DEFAULT_SOURCE_OPTIONS],
    note: "Kia K5. Ожидает звонок за 30 минут до готовности.",
    lastVisitDate: "16.03.2026",
    ordersCount: 2,
    averageCheck: 3570,
    totalSpent: 7140,
    averageVisitGapLabel: "2 дня",
    vehicles: [
      {
        id: "vehicle-kia-k5",
        label: "Kia K5",
        brand: "Kia",
        model: "K5",
        plateNumber: "Т412РК 196",
        radius: "R18",
        totalSpent: 7140,
      },
    ],
    orders: [
      {
        id: "client-order-62",
        orderNumber: "62",
        dateTime: "16 марта 2026, 13:20",
        branch: "Северный",
        carLabel: "Kia K5 · R18",
        amount: 2880,
        status: "Ожидает оплаты",
        servicesLabel: "Балансировка",
      },
      {
        id: "client-order-56",
        orderNumber: "56",
        dateTime: "14 марта 2026, 20:48",
        branch: "Северный",
        carLabel: "Kia K5 · R18",
        amount: 4260,
        status: "Оплачен",
        servicesLabel: "Комплекс шиномонтажа",
      },
    ],
    visits: [
      {
        id: "visit-anna-1",
        dateTime: "16.03.2026 · 13:20",
        branch: "Северный",
        post: "ПОСТ 1",
        serviceLabel: "Балансировка",
        resultLabel: "Выполнено",
      },
      {
        id: "visit-anna-2",
        dateTime: "14.03.2026 · 20:48",
        branch: "Северный",
        post: "ПОСТ 1",
        serviceLabel: "Комплекс шиномонтажа",
        resultLabel: "Оплачено",
      },
    ],
    storages: [],
    bookings: [
      {
        id: "booking-anna-1",
        date: "18.03.2026 · 19:00",
        note: "Весенний переобув",
      },
    ],
  },
  {
    id: "sergey-volkov",
    name: "Игорь Лебедев",
    shortName: "Игорь Лебедев",
    firstName: "Игорь",
    lastName: "Лебедев",
    middleName: "",
    phone: "+7 900 500-50-05",
    email: "",
    registrationDate: "10.03.2026",
    source: "Постоянный клиент",
    sourceOptions: [...DEFAULT_SOURCE_OPTIONS],
    note: "Toyota Camry. Просит бережно мыть колеса.",
    lastVisitDate: "14.03.2026",
    ordersCount: 2,
    averageCheck: 3260,
    totalSpent: 6520,
    averageVisitGapLabel: "4 дня",
    vehicles: [
      {
        id: "vehicle-toyota-camry",
        label: "Toyota Camry",
        brand: "Toyota",
        model: "Camry",
        plateNumber: "С777ОР 196",
        radius: "R18",
        totalSpent: 6520,
      },
    ],
    orders: [
      {
        id: "client-order-57",
        orderNumber: "57",
        dateTime: "14 марта 2026, 11:20",
        branch: "Северный",
        carLabel: "Toyota Camry · R18",
        amount: 2520,
        status: "Оплачен",
        servicesLabel: "Балансировка",
      },
      {
        id: "client-order-44",
        orderNumber: "44",
        dateTime: "10 марта 2026, 10:15",
        branch: "Центральный",
        carLabel: "Toyota Camry · R18",
        amount: 4000,
        status: "Оплачен",
        servicesLabel: "Комплекс шиномонтажа",
      },
    ],
    visits: [
      {
        id: "visit-sergey-1",
        dateTime: "14.03.2026 · 11:20",
        branch: "Северный",
        post: "ПОСТ 1",
        serviceLabel: "Балансировка",
        resultLabel: "Оплачено",
      },
      {
        id: "visit-sergey-2",
        dateTime: "10.03.2026 · 10:15",
        branch: "Центральный",
        post: "ПОСТ 1",
        serviceLabel: "Комплекс шиномонтажа",
        resultLabel: "Оплачено",
      },
    ],
    storages: [],
    bookings: [],
  },
];

export function getClientById(clientId: string) {
  return DEMO_CLIENTS.find((client) => client.id === clientId);
}
