import type { DemoStorageItem } from "@/features/storage/types";

export const DEMO_STORAGE_ITEMS: DemoStorageItem[] = [
  {
    id: "storage-1",
    storageNumber: "ХР-001",
    clientId: "denis-pavlov",
    clientName: "Андрей Климов",
    clientPhone: "+7 900 100-10-01",
    carBrand: "BMW",
    carModel: "3 серии",
    plateNumber: "О313АА 196",
    kitLabel: "Комплект колёс BMW R17",
    status: "На хранении",
    warehouseId: "warehouse-gotvalda-9",
    warehouseName: "Северный",
    shelfLabel: "2",
    cellLabel: "4",
    acceptedAt: "2026-03-15T10:15:00+05:00",
    releasedAt: null,
    note: "До осени 2026",
  },
  {
    id: "storage-3",
    storageNumber: "ХР-002",
    clientId: "boris-zelen",
    clientName: "Олег Никитин",
    clientPhone: "+7 900 300-30-03",
    carBrand: "LADA",
    carModel: "Largus",
    plateNumber: "Е220КУ 196",
    kitLabel: "Комплект шин Nokian R15",
    status: "Выдано",
    warehouseId: "warehouse-gotvalda-9",
    warehouseName: "Северный",
    shelfLabel: "1",
    cellLabel: "7",
    acceptedAt: "2026-03-07T15:40:00+05:00",
    releasedAt: "2026-03-13T11:05:00+05:00",
    note: "Выдано клиенту 13.03.2026",
  },
  {
    id: "storage-4",
    storageNumber: "ХР-003",
    clientId: "anna-sokolova",
    clientName: "Мария Волкова",
    clientPhone: "+7 900 400-40-04",
    carBrand: "Kia",
    carModel: "K5",
    plateNumber: "Т412РК 196",
    kitLabel: "Диски Kia R18",
    status: "Готово к выдаче",
    warehouseId: "warehouse-gotvalda-9",
    warehouseName: "Северный",
    shelfLabel: "3",
    cellLabel: "1",
    acceptedAt: "2026-03-11T13:25:00+05:00",
    releasedAt: null,
    note: "Самовывоз сегодня",
  },
];
